DROP DATABASE IF EXISTS Otto;

CREATE DATABASE Otto;

USE Otto;

CREATE TABLE Department (
PRIMARY KEY (id),
id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL
);

CREATE TABLE Roles(
PRIMARY KEY (id),
id INT AUTO_INCREMENT NOT NULL,
Title  VARCHAR(30),
Salary DECIMAL,
Department_id INTEGER
);

CREATE TABLE Employee (
PRIMARY KEY (id),
id INT AUTO_INCREMENT NOT NULL,
First_Name VARCHAR(30),
Last_Name VARCHAR(30),
Role_id INTEGER,
Manager_id INTEGER
);




SELECT * FROM  Department;
SELECT * FROM Roles;
SELECT * FROM Employee;

  