DROP DATABASE IF EXISTS Otto;

CREATE DATABASE Otto;

USE Otto;

CREATE TABLE Department (
PRIMARY KEY (id),
id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL
);

CREATE TABLE Role(
PRIMARY KEY (id),
id INT AUTO_INCREMENT NOT NULL,
Title  VARCHAR(30) NOT NULL,
Salary DECIMAL NOT NULL,
deparment_id INTEGER NOT NULL
);

CREATE TABLE Employee (
PRIMARY KEY (id),
id INT AUTO_INCREMENT NOT NULL,
First_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
Role_id INTEGER NOT NULL,
Manager_id INTEGER NOT NULL
);




SELECT * FROM  Department;
SELECT * FROM Role;
SELECT * FROM Employee;

  